version: '3'
services:
  java_app:
    container_name: java_app
    image: maxrprp/corporate-settlemen
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://java_db:5432/demo
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - java_db


  java_db:
    container_name: java_db
    image: postgres
    ports:
      - 5432
    environment:

      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: demo
    volumes:
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
