spring:
  application:
    name: corporate-settlemen
  datasource:
    password: mysecretpassword
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace
      type: trace
      stat: debug


comment: >
  jpa:
    defer-datasource-initialization: true
  sql:
    init:
      mode: always