spring:
  application:
    name: corporate-settlemen
  datasource:
    password: ${DATABASE_PASSWORD}
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace
      type: trace
      stat: debug


comment: >
  jpa:
    defer-datasource-initialization: true
  sql:
    init:
      mode: always